language: php

branches:
  only:
    - master
    - dev

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - secure: WBP3WNhjf0O936txDDLzIlknDhpv6JoEvS7EzlAuLa/ZoWVROjIvkv9fpGTFkdHzma1Hl5FR/z1JS57xTSH2Tmp4WIAlld85g9pl/Rrs/CO9UxczRiIS4SnNsZtPbkxXjjyPOpOeNkSM8gepwjTc4QyfP0dExKfvVy7OW9T+V+R2uXo3qbh8Dy0eAyC4TOJp8G3OUrry54jTat6c0Z0f+si1sFkpYf3oJo6PBCCz+rTP05NTnwYp+Mh74GKiepBDwwzL/fESRCp56y49bDoUosTkawrBFHBqxSEFwjfxUyZoK9VoVbRJ68GMz1hq3/amUl7oWPqmK9yiGbCJZKAL4L77g3odYLHzeG0Xk6DXMj5mKeEDBGjotgwMaeofNs7b/83ZU+r8KaI+ig9nj8H8AfJGTQ6b6ESSfoHHMUp5a5l6BCFSuFtH9W3eAPeCCHHtjjBYQ3ncSCkULfvEg4s+QleLraGQkYgpFlg1rhED6wYAD1yFJzPgQpmLoJYUtOsrEe+szHgHE2F4YxQ0usFwt8WOsqgfLTZya+MWh8BnpCOemXyubnW7Kwq5EnkOUbg8W7W1LPKheeiqq5KAIZkqi+lzebf7QiKhcKgeucbJTmrRc/5pVtro6pntQpC02UOoUNRsqbQQiTf04kfjICuzS9r7vDKD2TRi5dWEpqhIrNE=
    - secure: j5/UQVbs4dz1Aod+/9U9AW+Ds3oXMYdz4CDYfxtLwxh5i7cuKnzlxsiMGgtWHG+AjPoq2Ij3n/ZAqTDI+aFCB3DwoPJBdIHzJdMjSGnccOhlasyoq67KRDeEC9qrV6B59kxqFJWtW0iuk7MGm9uf9eh2VIXK5Jsie9mPqOZgJNpZ5sE9JGkys4g1TtnuUKKQBgCUPXKntONXYQh7obXnSCyjPfk1Ptf6ibIZFU3ISmqTIXB61jUREdCAZ8d5jLmb37vzUJ6iXHpSUt5WpWo7q3AYtULh1zzMKHAPh646yotyoZiJ+XE1FNhHQWqMoRWAUyuzqJvVwnH/+CtvL0nFm37iLnKAVJTxRb62ozUKtHJ232MCOxZgOqDWPnYnHUTPuKw3ARtUBP7FotmeiLNPeBhoNOBrkOJWPcvezdHcHMmq17VZOEoIuqG8OlvF2jcVpzJtYIKB/4r7SQ2DCNh6XP8dN48f/90ZO+HsC+fqnf7Hqy+03byZlM6PeH7Xgk+8PWhxQy12sSAL6DIT21NgGM7M8HYkEyjYEchHegGDwVWelE3vQ7tYcMFXybKafJq/lREnBq6KAd2TauaaERKr1PRhgjypOq/yZqxfVmSllgfD2R404xscD5kdclIGH+MxJyqR/bhGN8wGxA4AVvYZ8uyguamu6wLeK5TFv/HSk4g=

install:
  - travis_retry composer self-update
  - travis_retry composer install -n --prefer-source

before_script:
  - mkdir -p build/log

script:
  - vendor/bin/phpcs --standard=./phpcs.xml -v --encoding=utf-8 ./src
  - vendor/bin/phpunit -c phpunit.xml --debug

after_script:
  - php test/check-coverage.php build/log/clover.xml 50
